version: "3.9"
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    container_name: ${CONTAINER_NAME}
    ports:
      - "${HOST_PORT}:${APP_PORT}"
    environment:
      - APP_PORT=${APP_PORT}
      - APP_HOST=${APP_HOST}
      - APP_ENV=${APP_ENV}
